### ISSUE TITLE
Prevent the console from closing the application

### ISSUE THREAD

**Issue by rcases** [floooh/sokol#1425]
My application has implemented all the necessary mechanisms so that when the close button is pressed, it prompts the user before exiting and allows them to save their work.
However, if the console is open and the user presses the console's close button, the application closes immediately without the option to prompt the user or save their work. Could one of the solutions proposed in "https://stackoverflow.com/questions/20232685/how-can-i-prevent-my-program-from-closing-when-a-open-console-window-is-closed" be applied?

**Comment by floooh** [comment]
Hmm, assuming you're on Windows, I cannot reproduce this here...

For instance:

```
git clone https://github.com/floooh/pacman.c
cd pacman.c
mkdir build
cd build
cmake ..
cmake --build .
Debug/pacman.c
```

...the pacman.exe executable starts decoupled from the terminal (e.g. I can continue to enter new commands), and closing the terminal window keeps the application open.

This only works for 'WinMain' applications of course. E.g. in cmake you need to build using the `WIN32` arg in `add_executable()` which then tells the linker to build a 'Windows subsystem' application instead of a cmdline application using main(). E.g. in sokol_app.h you can set a breakpoint here to check is this is actually happening:

https://github.com/floooh/sokol/blob/bb551ededd63794e96314303558679931ed41beb/sokol_app.h#L9894-L9906

...the executable in cmake needs to be defined like this:

https://github.com/floooh/pacman.c/blob/fffe99f778688acaf8ff38ee5e3582c85293e163/CMakeLists.txt#L39

...other build systems probably have a similar option, or otherwise you'd need to tell the MSVC linker to build a "Windows subsystem application" so that it picks WinMain as entry point:

https://learn.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170

**Comment by rcases** [comment]
I don't think we're talking about the same thing.
I'm referring to this console:
```    
    sapp_desc desc = { };
    ...
    desc.win32.console_create = true;
```

**Comment by rcases** [comment]
I modified pacman by adding:
```
        if (ev->type == SAPP_EVENTTYPE_QUIT_REQUESTED)
        {
            sapp_cancel_quit();
        }
```
and 
```   
 .win32.console_create = true,
```
Now, if you press the close button in the main window, it doesn't close, but if you press the close button in the terminal, it does close.

<img width="1007" height="683" alt="Image" src="https://github.com/user-attachments/assets/22649bee-949d-447f-b796-f7f199714020" />

**Comment by floooh** [comment]
> desc.win32.console_create = true;

Ah ok...this is expected behaviour though, But creating a console for a Windows application to see its stdout is more or less a debugging feature, why do you need this for a real-world application?

**Comment by rcases** [comment]
The application's purpose is to send discrete commands to an instrument, such as sensor readings, motor movement, and firmware updates, to test the correct implementation of these commands.
The console output is used more for debugging the instrument than the application.
In this situation, accidentally closing the application from either window isn't a problem; you simply reopen it.

However, I'm currently adding the ability to run scripts so that testers can schedule lifecycle tests. In this situation, closing the console window without confirming could have a catastrophic impact on the test or result in the loss of unsaved data.

<img width="1918" height="1046" alt="Image" src="https://github.com/user-attachments/assets/2ecc7aa9-d99a-4149-8c54-d154b09d0a09" />

**Comment by floooh** [comment]
Hmm ok I see. The solutions in the StackOverflow link you linked all don't look that great tbh.

Did you consider capturing the stdout/stderr output and render it in a regular Dear Imgui window? I'll need to look up again how that works, but I definitely did that in the past and it wasn't too hard, and if it can't be done outside sokol_app.h then I would rather such a stdout/stderr capture feature to sokol_app.h.

But let me find some example code first...

**Comment by floooh** [comment]
Hmm, I only have some very old code lying around which captures stdout and stderr from a Win32 child process... this is on a launched child process, but it should also work on its own process... it's a bit more code than I remembered but also not too much...

https://gist.github.com/floooh/e4a781854c381df1cedb000895275892

...the only problem I have with integrating something like this into sokol_app.h would be that it is highly Windows specific, e.g. even if it becomes a sokol library it would probably be done better outside, and it doesn't really need anything from sokol_app.h, only a process handle (which can be obtained via GetCurrentProcess()), and 'draining' the stdout/stderr pipes works via polling.

**Comment by rcases** [comment]
Yes, capturing stdout/stderr was the alternative I was going to use.

**Comment by floooh** [comment]
> Yes, capturing stdout/stderr was the alternative I was going to use.

Tbh, that sounds like the much more robust solution to me :)

**Comment by rcases** [comment]
Yes, I plan to have a window for messages related to script execution, such as compilation errors and script printfs. Putting stdout/stderr messages here would add a lot of noise, so I preferred to keep the console output separate.

But anyway, nothing I can't handle with a window with different message tabs. As far as I'm concerned, the issue can be closed.

**Comment by rcases** [comment]
Ideally, I'd like to have the console messages in a separate viewport from the main one. 
Is there any estimate for when the multi-viewport feature might be available? :grin:

**Comment by floooh** [comment]
> Is there any estimate for when the multi-viewport feature might be available?

No, that will a while, don't hold your breath.
